### ISSUE TITLE
 simplify: Bad namespace URL http://jaxb2-commons.dev.java.net/basic/simplify

### ISSUE THREAD

**Issue by wltjr** [highsource/jaxb2-basics#86] opened 2017-09-27 16:20 UTC
java.net has been shutdown. This seems to cause issues as the namespace url is no longer valid.
http://jaxb2-commons.dev.java.net/basic/simplify I cannot find that file. Makes anything using it, not able to be usable via xjc/jaxb2. Thanks!

**Comment by highsource** [comment] 2017-09-27 16:55
`http://jaxb2-commons.dev.java.net/basic/simplify` *is* the valid namespace URI.

Namespaces are URIs ("identifiers"), *not* URLs ("resource locators"). A namespace URI does not need to point to some existing resource. It *may* but that is completely optional. As the matter of fact, there have never been any resource under `http://jaxb2-commons.dev.java.net/basic/simplify`, there is no (and never was) a "file" there. So the shutdown of java.net is completely irrelevant and has no influence on functionality of the plugin in xjc/jaxb2.

Now you seem to have a problem that you thought have been caused by "invalid namespace URL". Why don't you start with describing that problem - like, how you execute the plugin (ideally a build script/Maven pom), which error messages you get (complete log) etc.

**Comment by wltjr** [comment] 2017-09-27 17:04
Ok. Not to get into semantics but a URL is a URI. The fact that it has http makes it a URL, http://. I was not sure if the missing namespace mattered or not. I guess it does not matter. I am looking into building the plugins and using them. Seems they reside in the [javaee/jaxb2-commons](https://github.com/javaee/jaxb2-commons) repository. Once I build and package them, I can see about using the Simplify plugin. Maybe then the namespace will not matter. I think that is the first time I have come across a namespace/schema that has no source.

**Comment by highsource** [comment] 2017-09-27 17:20
> Not to get into semantics but a URL is a URI.

XML namespaces are URIs, not URLs. The `http://jaxb2-commons.dev.java.net/basic/simplify` as used in the plugin is a URI, not an URL. And URI, by definition "is a compact sequence of characters that identifies an abstract or physical resource". There is no requirement that it is a physical resource and that it actually exists and is accessible.

> Seems they reside in the javaee/jaxb2-commons repository.

JAXB2-Basics plugins including the Simplify plugin are hosted in [this very repository](https://github.com/highsource/jaxb2-basics), where you've filed this issue. See:

https://github.com/highsource/jaxb2-basics/tree/master/basic/src/main/java/org/jvnet/jaxb2_commons/plugin/simplify

> Once I build and package them, I can see about using the Simplify plugin.

Or you can get the JAR here:
http://repo1.maven.org/maven2/org/jvnet/jaxb2_commons/jaxb2-basics/0.11.1/

As it seems there was no actual problem with the plugin, I'm closing this issues as invalid.

**Comment by wltjr** [comment] 2017-09-27 17:24
I am packaging this stuff on Gentoo, building jars, not using them. This is actually something Hibernate is using. I was not sure what this repo relationship was to the plugin. I did not see it on maven.org, at least version wise etc. What is the relation between this one and the one under javaee?

**Comment by highsource** [comment] 2017-09-27 17:28
Historically JAXB2-Basics was a subproject of JAXB2 Commons (hosted on java.net). Later on I've moved my projects from java.net to GitHub, but some older repos probably remained on java.net.

**Closed** 2017-09-27 17:32 UTC
Labels: invalid
