### ISSUE TITLE
xjc:superClass not supported by copyable, equals and hashCode plugins

### ISSUE THREAD

**Issue by krokodylowy** [highsource/jaxb2-basics#42] opened 2015-12-12 22:54 UTC
I got almost correctly class generated from definitions. Almost because  clone, hashCode, equals, copyTo don't use the same methods from superClass so some data in clone and equals are missing.
My generated class x extends y implements Cloneable, CopyTo, Serializable, 
class y implements Cloneable, CopyTo, Serializable.

Copyable plugin code got some superClass code but it seems to me it's not executed.
How to configure plugin to generate correct method clone which also cloning attributes from superclass?

**Comment by highsource** [comment] 2015-12-13 09:27
This should actually work. Please show your generated code, send a PR with the reproducing test project.

**Comment by krokodylowy** [comment] 2015-12-13 14:24
OK. I write some but at this moment I see that test use only <xsd:extension base="a:AType"> notation
and not use something like
<xs:annotation>
		<xs:appinfo>
			<jaxb:globalBindings choiceContentProperty="true" generateIsSetMethod="true">
				
				<xjc:superClass name="mco.AbstractMDObject" />
			</jaxb:globalBindings>
	</xs:annotation>

or <xjc:superInterface name="com.example.model.Person"/>

**Comment by krokodylowy** [comment] 2015-12-13 17:38
[testcase.txt](https://github.com/highsource/jaxb2-basics/files/60539/testcase.txt)
Attached patch for git. 
Episode c for jaxb2-basics\tests\episodes\c.  Class BType extends AbstractMDObject.java
AbstractMDObject.java included in Episode a.
Clone,hashCode and equals ignore attributes from AbstractMDObject.

Such kind of extension is a part of bigger real project.

**Comment by highsource** [comment] 2015-12-13 18:13
I can't apply the diff you sent, sorry. It modifies the `episodes` project. I'd prefer not to hack an existing project for the new issue.

I see what the problem is:

* Superclasses or superinterfaces defined via `xjc:superClass` or `xjc:superInterface`
* Class references via `jaxb:class/@ref` via episode files.

Actually all of this should work. Plugins [check if the superclass implements the expected interface](https://github.com/highsource/jaxb2-basics/blob/master/basic/src/main/java/org/jvnet/jaxb2_commons/plugin/util/StrategyClassUtils.java#L56-L81).

But this only works if the superclass is known during the code generation time. It must be compiled before and be present in the classpath when the code is generated.

You've added `test.AbstractMDObject` as superclass for every class in the `episode/a` project. But you've placed this class in the same project. It's not compiled before so plugin's can't (easily) check if `AbstractMDObject` implements `CopyTo` or any other interface in question. It's only present as a source code and, just from the source code, it's not easy to check, if the class implements a certain interface. It's not impossible, but it's quite hard to do correctly.

So what you should do is:

* Create a new module which you compile before you generate code from you schemas.
* Move your superclasses (`AbstractMDObject` and likes) to this module.
* Compile it and include it into the classpath of the schema compiler.

I think this should work with the current code. If not, we'll have to make a (new) reproducing test project for this under https://github.com/highsource/jaxb2-basics/tree/master/tests.

I'd also be grateful if you'd send me a pull request next time instead of a git diff. Working with PRs is  much easier in GitHub, it's *the* way to provide project changes on GitHub.

**Comment by krokodylowy** [comment] 2015-12-13 19:17
>    Create a new module which you compile before you generate code from you schemas.
>    Move your superclasses (AbstractMDObject and likes) to this module.
>    Compile it and include it into the classpath of the schema compiler.
My code already did it.  Module a  contains AbstractMDObject and is on the classpath and pom dependecies in b module.  B module compiled correcty and generated output contains B extends AbstractMDObject code only some methods is not generated correctly

**Comment by krokodylowy** [comment] 2015-12-14 10:02
Adding autoInheritance also do not resolve problem with equals,clone and hashSet
`<arg>-XautoInheritance</arg>
<arg>-XautoInheritance-xmlTypesExtend=test.AbstractMDObject</arg>`

**Comment by krokodylowy** [comment] 2015-12-14 10:26
A partial workaround exist for equals and hashCode (not clone)
Correct equals and hashCode is generated if bindings.xml is extended with
`<jaxb:bindings
			node="xs:complexType[@name='BType']">
			 <inheritance:extends>test.AbstractMDObject</inheritance:extends>
		</jaxb:bindings>`
In above case equals and hashCode call's super.equals ans super.hashCode.
super.copyTo isn't called

**Comment by highsource** [comment] 2015-12-15 08:20
I've reproduced it now, `xjc:superClass` is indeed not considered by the
plugins. It's quite easy to correct.

Do you have further issues with superclasses apart from `xjc:superClass`?

**Comment by krokodylowy** [comment] 2015-12-15 13:25
No. Just #43.

BTW.
As a temporary workaround I mixed xjc:superClass with inheritance:extends and results are good but
bindings code looks ugly now.

**Comment by highsource** [comment] 2015-12-16 18:53
This should be fixed now, please give it a try.

Should work both with `xjc:superClass` and `xjc:superInterface`.

**Closed** 2015-12-18 08:33 UTC
Labels: enhancement
